- name: Java + Zookeeper
  hosts: all
  remote_user: ubuntu
  become: true
  roles:
    - role: geerlingguy.java
  vars:
    zookeeper_hostnames: "{{ groups.zookeeper_hosts | join(':' + zookeeper_client_port + ',') }}:{{ zookeeper_client_port }}"
    mesos_cluster_name: "LOFAR rules"



- name: Mesos [master]
  hosts: master
  remote_user: ubuntu
  become: true
  roles:
    - role: JasonGiedymin.mesos
      mesos_install_mode: master

- name: Mesos [slave]
  hosts: slave
  remote_user: ubuntu
  become: true
  roles:
    - role: JasonGiedymin.mesos
      mesos_install_mode: slave
      mesos_containerizers: "docker,mesos"

- name: Zookeeper
  hosts: zookeepers
  sudo: yes
  remote_user: ubuntu
  roles:
    - role: AnsibleShipyard.ansible-zookeeper
      zookeeper_hosts: "{{groups['zookeepers']}}"
