
- name: master
  hosts: master
  remote_user: ubuntu
  become: true
  tasks:
    - import_tasks: tasks/mesos.yml
    - import_tasks: tasks/zookeeper.yml
    - apt:
        pkg={{ item }} state=present update_cache=yes
      with_items:
        - marathon
        - chronos

- name: slave
  hosts: slave
  remote_user: ubuntu
  become: true
  tasks:
    - import_tasks: tasks/mesos.yml
