- hosts: all
  strategy: free
  remote_user: ubuntu
  become: true
  tasks:
    - import_tasks: tasks/cwl.yml
    - import_tasks: tasks/kern.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/singularity.yml
    - import_tasks: tasks/prefactor.yml
