---
- name: install required packages
  apt: name={{item}} state=installed
  with_items:
    - python-setuptools
    - python-pip
    - python-pkg-resources
    - nodejs-legacy
    - python-dev

- name: install cwltool
  pip: name={{item}}
  with_items:
    - cwltool
    - git+git://github.com/BD2KGenomics/toil.git@4c234e6b793737e9fa88019941241062b30c97c7#egg=toil[cwl]
    - boto
    - pycrypto
    - html5lib