---
- name: Add apt-key
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: Add mesosphere repo
  apt_repository: repo='deb http://repos.mesosphere.com/ubuntu {{ ansible_distribution_release | lower }} main' state=present update_cache=yes

- name: Install Debian OS packages
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - wget
    - curl
    - unzip
    - python-setuptools
    - python-dev
    - mesos

- name: create zookeeper file
  template:
      src: "templates/zk"
      dest: "/etc/mesos/zk"

